return {
  Samus = {
    date = "1986",
    cameo = "Metroid",
    ["premiere_apparition"] = "NES Metroid",
    serie = "Metroid",
  },
  Fox = {
    date = "1993",
    ["premiere_apparition"] = "Star Fox",
    createur = "Shigeru Miyamoto",
    cameo = "Super Smash Bros",
    serie = "Star Fox",
  },
  Marth = {
    date = "1990",
    cameo = "Super Smash Bros",
    ["premiere_apparition"] = "Fire Emblem",
    serie = "Fire Emblem",
  },
  Mewtwo = {
    createur = "Ken Sugimori",
    cameo = "Pokemon Red and Blue",
  },
  Mario = {
    date = "1981",
    ["premiere_apparition"] = "Donkey Kong",
    createur = "Shigeru Miyamoto",
    cameo = "Donkey Kong",
    serie = "Mario",
  },
  Isabelle = {
    date = "2012",
    cameo = "Super Smash Bros",
    ["premiere_apparition"] = "Animal Crossing",
  },
  Luigi = {
    createur = "Shigeru Miyamoto",
    cameo = "Mario Bros",
    ["premiere_apparition"] = "Mario Bros",
    date = "1983",
  },
  Ganon = {
    createur = "Shigeru Miyamoto",
    cameo = "The Wind Waker",
    ["premiere_apparition"] = "The Legend Of Zelda",
    date = "1986",
  },
  Ridley = {
    createur = "Makoto Kano",
    cameo = "Super Smash Bros",
    ["premiere_apparition"] = "Metroid",
    date = "1986",
  },
  Zelda = {
    createur = "Shigeru Miyamoto",
    cameo = "The Legend of Zelda du systeme",
    ["premiere_apparition"] = "The Legend",
    serie = "The Legend of Zelda",
  },
  Olimar = {
    createur = "Shigeru Miyamoto",
    cameo = "Nintendo",
    ["premiere_apparition"] = "Pikmin",
    date = "2001",
  },
  Snake = {
    createur = "Hideo Kojima",
    cameo = "Scribblenauts",
    ["premiere_apparition"] = "Metal Gear",
    date = "1987",
  },
  Palutena = {
    createur = "Gunpei Yokoi",
    ["premiere_apparition"] = "Kid Icarus",
    date = "1986",
  },
  Shulk = {
    createur = "Tetsuya Takahashi",
    ["premiere_apparition"] = "Xenoblade Chronicles",
    date = "2010",
  },
  Rondoudou = {
    date = "151",
    ["premiere_apparition"] = "Pokemon Red",
    createur = "Ken Sugimori",
    cameo = "Pokemon Red and Blue",
    serie = "Pokemon",
  },
  ["Donkey Kong"] = {
    createur = "Shigeru Miyamoto",
    cameo = "Donkey Kong",
    ["premiere_apparition"] = "Donkey Kong",
    date = "1981",
  },
  Link = {
    createur = "Shigeru Miyamoto",
    cameo = "Super Mario Bros",
    date = "1987",
    serie = "The Legend of Zelda",
  },
  Kirby = {
    date = "1992",
    ["premiere_apparition"] = "Game Boy Kirby",
    createur = "Masahiro Sakurai",
    cameo = "Super Smash Bros",
    serie = "Kirby",
  },
  Yoshi = {
    date = "1992",
    ["premiere_apparition"] = "Super Mario World",
    createur = "Kazumi Totaka",
    cameo = "Super Mario World",
    serie = "Smash",
  },
  Bowser = {
    createur = "Shigeru Miyamoto",
    cameo = "Super Mario Bros",
    ["premiere_apparition"] = "Super Mario Bros",
    date = "1985",
  },
  Felinferno = {
    ["premiere_apparition"] = "VII",
  },
  Wario = {
    date = "1992",
    ["premiere_apparition"] = "Game Boy",
    createur = "Hiroji Kiyotake",
    cameo = "Game Boy",
    serie = "Mario",
  },
  Cloud = {
    createur = "Tetsuya Nomura",
    cameo = "Cloud",
  },
  Pichu = {
    createur = "Pichu",
    cameo = "Pokemon HeartGold",
    ["premiere_apparition"] = "II",
  },
  ["Captain Falcon"] = {
    createur = "Shigeru Miyamoto",
    ["premiere_apparition"] = "FZERO",
    date = "1991",
  },
  Ness = {
    date = "1994",
    cameo = "Nintendo jeu",
    ["premiere_apparition"] = "Earthbound",
    serie = "EarthBound",
  },
  Pikachu = {
    date = "1996",
    ["premiere_apparition"] = "generation Red",
    createur = "Satoshi Tajiri",
    cameo = "Super Smash Bros",
    serie = "Pokemon",
  },
  Ike = {
    cameo = "Super Smash Bros",
  },
  Peach = {
    createur = "Shigeru Miyamoto",
    cameo = "Mario",
    serie = "Mario",
  },
  Rosalina = {
    createur = "Shigeru Miyamoto",
    cameo = "Mario Kart recemment",
  },
  ["Samus sombre"] = {
    date = "2004",
    cameo = "Super Smash Bros",
    ["premiere_apparition"] = "Metroid Prime",
    serie = "Metroid",
  },
  ["Meta Knight"] = {
    date = "1993",
    ["premiere_apparition"] = "Kirby",
    serie = "Kirby",
  },
}